### PR TITLE
Fix socket connection fail message bug

### LINKED ISSUE #36: [BUG] Both `onerror` and `onclose` are triggered when socket connection fails to be initialized
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

pnls-web-socket-bug

This shouldn't be the case. Only the `onerror` should be triggered, meaning only the "*Can't establish connection to the server!*" should be displayed.

### PNLS version

0.2.0

### Python version

_No response_

### Operating system

_No response_

### Additional environment/system information

_No response_

### Actual Behavior

Both messages, "*Can't establish connection to the server!*" and "*Connection to the server has been terminated!*" are displayed.

### Expected Behavior

Only "*Can't establish connection to the server!*" message should be shown.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AleksaMCode**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Security Fix
- [x] Bug Fix
- [x] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## Description

Only "*Can't establish connection to the server!*" message should be shown when socket connection fails to be initialized.

## Related Tickets & Documents

- Closes #36 

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: _testing not utilized at this point_
- [ ] I need help with writing tests

### CODE REVIEW

File: web/src/components/pnlData/index.js [hunk 1]
```diff
@@ -45,7 +51,7 @@ export const PnlData = () => {
       ws.removeEventListener('close', handleClose)
       ws.close()
     }
-  }, [ws])
```
Comment (AleksaMCode) [inline web/src/components/pnlData/index.js:48]: Dependency array has been updated - The `WebSocket` connection will be established when the component mounts and cleaned up when it unmounts.
